name = "monsterworld-api"
main = "worker.js"
compatibility_date = "2026-07-01"

# после `wrangler kv namespace create SNAPS` вставь сюда выданный id
[[kv_namespaces]]
binding = "SNAPS"
id = "6aa2b5ec131542dbbd2a5c6a388d63e0"
